namespace Booking.API.Controllers;

/// <summary>
/// Event Management Endpoints
/// Handles creation and management of events
/// </summary>
[ApiController]
[Route("api/[controller]")]
public sealed class EventsController : BaseController
{
    public EventsController(ISender sender) : base(sender) { }

    /// <summary>
    /// Create a new event with optional category-wise seat allocation
    /// </summary>
    /// <remarks>
    /// Creates a new event in the system. The event will be in unpublished state initially.
    /// Optionally, seats can be auto-generated by specifying category-wise seat counts.
    /// 
    /// Sample request without seats:
    /// 
    ///     POST /api/events/create
    ///     {
    ///        "title": "Taylor Swift - Eras Tour",
    ///        "description": "The biggest concert of the year",
    ///        "startDateTime": "2026-06-15T20:00:00Z",
    ///        "venueName": "MetLife Stadium"
    ///     }
    ///     
    /// Sample request with category-wise seats:
    /// 
    ///     POST /api/events/create
    ///     {
    ///        "title": "Taylor Swift - Eras Tour",
    ///        "description": "The biggest concert of the year",
    ///        "startDateTime": "2026-06-15T20:00:00Z",
    ///        "venueName": "MetLife Stadium",
    ///        "categoryWiseSeats": [
    ///           {"category": "VIP Premium", "seatType": "VIP", "count": 100, "row": "A", "price": 500.00},
    ///           {"category": "Regular", "seatType": "Regular", "count": 200, "row": "B", "price": 250.00},
    ///           {"category": "Economy", "seatType": "Economy", "count": 300, "row": "C", "price": 100.00}
    ///        ]
    ///     }
    /// </remarks>
    /// <param name="command">Event creation details including optional category-wise seats</param>
    /// <param name="cancellationToken">Cancellation token</param>
    /// <returns>Created event with assigned ID and seat information if provided</returns>
    /// <response code="201">Event created successfully</response>
    /// <response code="400">Invalid input or validation error</response>
    /// <response code="500">Server error</response>
    [HttpPost("create")]
    [ProducesResponseType(StatusCodes.Status201Created)]
    [ProducesResponseType(StatusCodes.Status400BadRequest)]
    [ProducesResponseType(StatusCodes.Status500InternalServerError)]
    public async Task<IActionResult> Create(
        [FromBody] CreateEventCommand command,
        CancellationToken cancellationToken)
    {
        if (!ModelState.IsValid)
            return BadRequest(ModelState);

        var result = await _sender.Send(command, cancellationToken);
        return result.IsSuccess 
            ? CreatedAtAction(nameof(Create), new { id = result.Data?.Id }, result)
            : BadRequest(result);
    }

    /// <summary>
    /// Get available seats for an event
    /// </summary>
    /// <remarks>
    /// Retrieves all available seats (not held, reserved, or sold) for a specific event.
    /// This list changes in real-time as users place holds and make reservations.
    /// </remarks>
    /// <param name="eventId">Event ID to query</param>
    /// <param name="cancellationToken">Cancellation token</param>
    /// <returns>List of available seats</returns>
    /// <response code="200">Available seats retrieved successfully</response>
    /// <response code="404">Event not found</response>
    /// <response code="500">Server error</response>
    [HttpGet("{eventId:guid}/available-seats")]
    [ProducesResponseType(StatusCodes.Status200OK)]
    [ProducesResponseType(StatusCodes.Status404NotFound)]
    [ProducesResponseType(StatusCodes.Status500InternalServerError)]
    public async Task<IActionResult> GetAvailableSeats(
        [FromRoute] Guid eventId,
        CancellationToken cancellationToken)
    {
        if (eventId == Guid.Empty)
            return BadRequest("Event ID cannot be empty");

        var query = new GetAvailableSeatsQuery(eventId);
        var result = await _sender.Send(query, cancellationToken);

        return result.IsSuccess 
            ? Ok(result)
            : NotFound(result);
    }

    /// <summary>
    /// Get all seats for an event with their current status
    /// </summary>
    /// <remarks>
    /// Retrieves all seats (Available, Held, Reserved, Sold) for a specific event.
    /// Each seat shows its current status and other details including pricing and location.
    /// Seats are sorted by row and number for better readability.
    /// </remarks>
    /// <param name="eventId">Event ID to query</param>
    /// <param name="cancellationToken">Cancellation token</param>
    /// <returns>List of all seats with their current status</returns>
    /// <response code="200">All seats retrieved successfully</response>
    /// <response code="404">Event not found</response>
    /// <response code="500">Server error</response>
    [HttpGet("{eventId:guid}/all-seats")]
    [ProducesResponseType(StatusCodes.Status200OK)]
    [ProducesResponseType(StatusCodes.Status404NotFound)]
    [ProducesResponseType(StatusCodes.Status500InternalServerError)]
    public async Task<IActionResult> GetAllSeats(
        [FromRoute] Guid eventId,
        CancellationToken cancellationToken)
    {
        if (eventId == Guid.Empty)
            return BadRequest("Event ID cannot be empty");

        var query = new GetAllSeatsQuery(eventId);
        var result = await _sender.Send(query, cancellationToken);

        return result.IsSuccess
            ? Ok(result)
            : NotFound(result);
    }

    /// <summary>
    /// Get category-wise seat count and status breakdown for an event
    /// </summary>
    /// <remarks>
    /// Retrieves a summary of seats grouped by category (VIP, Regular, Economy).
    /// Shows the count of seats in each status for each category:
    /// - Total: Total seats in the category
    /// - Available: Free seats that can be booked
    /// - Held: Seats currently held by users (will expire in 10 minutes if not confirmed)
    /// - Reserved: Seats with confirmed bookings awaiting payment
    /// - Sold: Seats with completed transactions
    /// </remarks>
    /// <param name="eventId">Event ID to query</param>
    /// <param name="cancellationToken">Cancellation token</param>
    /// <returns>Category-wise seat summary with status breakdown</returns>
    /// <response code="200">Category-wise seat count retrieved successfully</response>
    /// <response code="404">Event not found</response>
    /// <response code="500">Server error</response>
    [HttpGet("{eventId:guid}/category-wise-seats")]
    [ProducesResponseType(StatusCodes.Status200OK)]
    [ProducesResponseType(StatusCodes.Status404NotFound)]
    [ProducesResponseType(StatusCodes.Status500InternalServerError)]
    public async Task<IActionResult> GetCategoryWiseSeatCount(
        [FromRoute] Guid eventId,
        CancellationToken cancellationToken)
    {
        if (eventId == Guid.Empty)
            return BadRequest("Event ID cannot be empty");

        var query = new GetCategoryWiseSeatCountQuery(eventId);
        var result = await _sender.Send(query, cancellationToken);

        return result.IsSuccess
            ? Ok(result)
            : NotFound(result);
    }
}
