namespace Booking.Application.Features.Events.Commands.CreateEvent;

/// <summary>
/// Command for creating a new event with category-wise seat allocation.
/// Seats can be optionally auto-generated by specifying seat counts per category.
/// </summary>
public sealed record CreateEventCommand(
    string Title,
    string Description,
    DateTime StartDateTime,
    string VenueName,
    List<CreateCategoryWiseSeatDto>? CategoryWiseSeats = null
) : IRequest<Response<EventWithSeatsDto>>;

/// <summary>
/// DTO for specifying seats during event creation.
/// Includes category, seat type, quantity, and row assignment.
/// </summary>
public sealed record CreateCategoryWiseSeatDto(
    string Category,
    string SeatType,
    int Count,
    string Row,
    decimal Price);
